export const databasesTypes = {
  FETCH_DATABASES_REQUEST: "FETCH_DATABASES_REQUEST",
  FETCH_DATABASES_SUCCESS: "FETCH_DATABASES_SUCCESS",
  FETCH_DATABASES_FAILURE: "FETCH_DATABASES_FAILURE",

  FETCH_DATABASE_REQUEST: "FETCH_DATABASE_REQUEST",
  FETCH_DATABASE_SUCCESS: "FETCH_DATABASE_SUCCESS",
  FETCH_DATABASE_FAILURE: "FETCH_DATABASE_FAILURE",

  CREATE_DATABASE_REQUEST: "CREATE_DATABASE_REQUEST",
  CREATE_DATABASE_SUCCESS: "CREATE_DATABASE_SUCCESS",
  CREATE_DATABASE_FAILURE: "CREATE_DATABASE_FAILURE",

  DISMISS_CONNECTION: "DISMISS_CONNECTION",
  CHECK_DATABASE_CONNECTION_REQUEST: "CHECK_DATABASE_CONNECTION_REQUEST",
  CHECK_DATABASE_CONNECTION_SUCCESS: "CHECK_DATABASE_CONNECTION_SUCCESS",
  CHECK_DATABASE_CONNECTION_FAILURE: "CHECK_DATABASE_CONNECTION_FAILURE",
};
