export const groupsTypes = {
  FETCH_GROUPS_REQUEST: "FETCH_GROUPS_REQUEST",
  FETCH_GROUPS_SUCCESS: "FETCH_GROUPS_SUCCESS",
  FETCH_GROUPS_FAILURE: "FETCH_GROUPS_FAILURE",

  FETCH_GROUP_REQUEST: "FETCH_GROUP_REQUEST",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",

  CREATE_GROUP_REQUEST: "CREATE_GROUP_REQUEST",
  CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
  CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE",

  SHOW_CREATE_GROUP_MODAL: "SHOW_CREATE_GROUP_MODAL",
  DISMISS_CREATE_GROUP_MODAL: "DISMISS_CREATE_GROUP_MODAL",

  SHOW_ADD_DATABASE_TO_GROUP_MODAL: "SHOW_ADD_DATABASE_TO_GROUP_MODAL",
  DISMISS_ADD_DATABASE_TO_GROUP_MODAL: "DISMISS_ADD_DATABASE_TO_GROUP_MODAL",
  SHOW_ADD_PROJECT_TO_GROUP_MODAL: "SHOW_ADD_PROJECT_TO_GROUP_MODAL",
  DISMISS_ADD_PROJECT_TO_GROUP_MODAL: "DISMISS_ADD_PROJECT_TO_GROUP_MODAL",
  SHOW_JOIN_GROUP_MODAL: "SHOW_JOIN_GROUP_MODAL",
  DISMISS_JOIN_GROUP_MODAL: "DISMISS_JOIN_GROUP_MODAL",
};
