export const projectTypes = {
  FETCH_PROJECTS_REQUEST: "FETCH_PROJECTS_REQUEST",
  FETCH_PROJECTS_SUCCESS: "FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_FAILURE: "FETCH_PROJECTS_FAILURE",
  FETCH_PROJECT_REQUEST: "FETCH_PROJECT_REQUEST",
  FETCH_PROJECT_SUCCESS: "FETCH_PROJECT_SUCCESS",
  FETCH_PROJECT_FAILURE: "FETCH_PROJECT_FAILURE",

  UPDATE_PROJECT_FROM_WS: "UPDATE_PROJECT_FROM_WS",
  CLEAR_NOTIFICATIONS: "CLEAR_NOTIFICATIONS",

  SELECT_PROJECTS_TO_SHOW: "SELECT_PROJECTS_TO_SHOW",

  MAKE_PREDICTION_REQUEST: "MAKE_PREDICTION_REQUEST",
  MAKE_PREDICTION_SUCCESS: "MAKE_PREDICTION_SUCCESS",
  MAKE_PREDICTION_FAILURE: "MAKE_PREDICTION_FAILURE",

  FETCH_PROJECTS_LITE_REQUEST: "FETCH_PROJECTS_LITE_REQUEST",
  FETCH_PROJECTS_LITE_SUCCESS: "FETCH_PROJECTS_LITE_SUCCESS",
  FETCH_PROJECTS_LITE_FAILURE: "FETCH_PROJECTS_LITE_FAILURE",
};

export const types = {
  ALL: "ALL",
  REGRESSION: "REGRESSION",
  CLASSIFICATION: "CLASSIFICATION",
};
